[project]
name = "samson"
version = "0.0.1"
description = "test task blender"
readme = "README.md"
requires-python = ">=3.10"

[tool.black]
line-length = 79
target-version = ['py310']
exclude = '''
/(
    \.git
  | .tox
  | .venv
  | venv
  | build
  | dist
  )/
'''
