# Generated by Django 4.2.10 on 2025-06-27 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LightType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_light",
                    models.CharField(
                        choices=[
                            ("point light", "точечный свет"),
                            ("spot light", "прожектор"),
                            ("sun light", "солнечный свет"),
                            ("area light", "плоский свет"),
                        ],
                        default="point light",
                        help_text="type light in scene",
                        max_length=150,
                        verbose_name="type light",
                    ),
                ),
                (
                    "energy",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="light energy",
                        verbose_name="energy",
                    ),
                ),
                (
                    "light color in HEX",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$"
                            )
                        ],
                        verbose_name="color",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Model3D",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time create",
                        verbose_name="created at",
                    ),
                ),
                (
                    "json_data",
                    models.FileField(
                        help_text="path to data json",
                        upload_to="json",
                        verbose_name="data json",
                    ),
                ),
                (
                    "scene_file",
                    models.FileField(
                        help_text="scene file path",
                        upload_to="3d_models/",
                        verbose_name="scene file",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Texture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texture_path",
                    models.ImageField(
                        help_text="path to texture",
                        upload_to="textures/",
                        verbose_name="texture path",
                    ),
                ),
            ],
        ),
    ]
